version: 2.5.8
jobs:
  build:
    working_directory: ~/rails-training

    docker:
      - image: circleci/ruby:2.5-stretch-node
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          DATABASE_URL: postgres://postgres@127.0.0.1:5432/wbooks-api_test

      - image: 'redis:4.0-alpine'

      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: wbooks-api_test
          POSTGRES_PASSWORD:
            

    steps:
      - checkout

      - run: echo "USING CIRCLE 2.0"

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      - run:
          name: Bundle install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: bundle show rails

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load --trace

      - run:
          name: Run Rubocop
          command: bundle exec rubocop app --format simple

      # Run Tests!
      - run:
         name: Run Tests
         command: bundle exec rspec 

workflows:
  version: 2
  build:
    jobs:
      - build